### ISSUE TITLE
failed to compile on RHEL 6.4 undefined reference to `CUPS_SRAND'

### ISSUE THREAD

**Issue by michaelrsweet** [michaelrsweet/htmldoc#271]
Version: 1.8.28
Original reporter: Mykola Sokolov

Impossible to compile HTMLDOC 1.8.28 on Red Hat Enterprise Linux Server release 6.4 (Santiago).

I'm attaching confi.log

Making all in htmldoc...
Compiling gui.cxx...
Compiling file.c...
Compiling html.cxx...
Compiling htmldoc.cxx...
Compiling htmllib.cxx...
Compiling htmlsep.cxx...
Compiling http.c...
http.c: In function 'httpInitialize':
http.c:1232: warning: implicit declaration of function 'CUPS_SRAND'
http.c:1235: warning: implicit declaration of function 'CUPS_RAND'
Compiling http-addr.c...
Compiling http-addrlist.c...
Compiling http-support.c...
Compiling image.cxx...
Compiling iso8859.cxx...
Compiling license.cxx...
Compiling md5.c...
Compiling progress.cxx...
Compiling ps-pdf.cxx...
ps-pdf.cxx: In function 'void ps_ascii85(FILE*, uchar*, int, int)':
ps-pdf.cxx:9865: warning: 'b' may be used uninitialized in this function
Compiling rc4.c...
Compiling snprintf.c...
Compiling string.c...
Compiling toc.cxx...
Compiling util.cxx...
Linking htmldoc...
http.o: In function `httpInitialize':
/home/sokomyk/tmp/htmldoc-1.8.28/htmldoc/http.c:1232: undefined reference to `CUPS_SRAND'
/home/sokomyk/tmp/htmldoc-1.8.28/htmldoc/http.c:1235: undefined reference to `CUPS_RAND'
collect2: ld returned 1 exit status
make[1]: *** [htmldoc] Error 1
